#!/bin/bash

cat <<EOF
// Autogenerated via ./gen_android_bp.sh
//
// Copyright (C) 2019 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

cc_prebuilt_binary {
  name: "common_crosvm",
  stem: "crosvm",
  srcs: ["scripts/crosvm"],
  defaults: ["cuttlefish_host_only"],
}

// NOTE: Using cc_prebuilt_binary because cc_prebuild_library can't handle stem on pie

EOF

for i in */bin/*; do
  if [[ ! -L "$i" ]]
  then
    name="${i//\//_}"
    name="${name//-/_}"
    name="${name/_bin_/_}"
    path="$(dirname $(dirname "$i"))"
    stem="$(basename "$i")"

    if [[ "crosvm" == "${stem}" ]]; then
      cat <<EOF
cc_prebuilt_binary {
  name: "${name}",
  srcs: ["${i}"],
  stem: "${stem}",
  relative_install_path: "${path}",
  defaults: ["cuttlefish_host_only"],
}
EOF
    else
      cat <<EOF
cc_prebuilt_binary {
  name: "${name}_for_crosvm",
  srcs: ["${i}"],
  stem: "${stem}",
  relative_install_path: "${path}",
  defaults: ["cuttlefish_host_only"],
}
EOF
    fi
  fi
done
